import type { Config } from "tailwindcss";
import forms from "@tailwindcss/forms";
import containerQueries from "@tailwindcss/container-queries";

const config: Config = {
  darkMode: "class",
  content: ["./src/**/*.{js,ts,jsx,tsx,mdx}"],
  theme: {
    extend: {
      colors: {
        "primary-fixed-dim": "#c5c0ff",
        "tertiary-fixed-dim": "#efc04c",
        "surface-container-highest": "#e5e2da",
        "on-surface-variant": "#474552",
        "on-secondary": "#ffffff",
        "on-primary-container": "#fffbff",
        "surface-dim": "#dcdad2",
        "on-primary-fixed": "#140067",
        outline: "#787583",
        "inverse-primary": "#c5c0ff",
        "tertiary-fixed": "#ffdf98",
        "surface-tint": "#5951b4",
        "surface-container-lowest": "#ffffff",
        surface: "#fcf9f1",
        "on-primary-fixed-variant": "#41379b",
        "on-tertiary-fixed": "#251a00",
        "on-secondary-container": "#007151",
        "on-secondary-fixed": "#002115",
        error: "#ba1a1a",
        "surface-container": "#f0eee5",
        "on-primary": "#ffffff",
        "on-error-container": "#93000a",
        "secondary-fixed": "#86f8c9",
        "surface-bright": "#fcf9f1",
        "secondary-container": "#83f5c6",
        "secondary-fixed-dim": "#68dbae",
        background: "#fcf9f1",
        "inverse-on-surface": "#f3f1e8",
        "surface-container-low": "#f6f4eb",
        "outline-variant": "#c8c4d4",
        tertiary: "#745800",
        secondary: "#006c4e",
        "surface-container-high": "#eae8e0",
        "error-container": "#ffdad6",
        "surface-variant": "#e5e2da",
        "on-error": "#ffffff",
        "on-secondary-fixed-variant": "#00513a",
        "primary-container": "#7067cc",
        primary: "#574eb1",
        "on-tertiary-container": "#fffbff",
        "on-tertiary-fixed-variant": "#5a4300",
        "primary-fixed": "#e4dfff",
        "tertiary-container": "#926f00",
        "on-surface": "#1c1c17",
        "on-tertiary": "#ffffff",
        "on-background": "#1c1c17",
        "inverse-surface": "#31312b",
        "action-teal": "#1d9e75",
        "action-amber": "#ef9f27",
        "action-neutral": "#888780",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        grid_margin: "32px",
        stack_gap_sm: "8px",
        stack_gap_md: "16px",
        container_padding: "24px",
        sidebar_width: "240px",
        grid_gutter: "24px",
        stack_gap_lg: "24px",
      },
      fontFamily: {
        sans: ["var(--font-inter)", "Inter", "sans-serif"],
        "body-lg": ["var(--font-inter)", "Inter"],
        "mono-label": ["var(--font-inter)", "Inter"],
        "body-md": ["var(--font-inter)", "Inter"],
        h2: ["var(--font-inter)", "Inter"],
        h1: ["var(--font-inter)", "Inter"],
        "label-sm": ["var(--font-inter)", "Inter"],
        h3: ["var(--font-inter)", "Inter"],
      },
      fontSize: {
        "body-lg": ["16px", { lineHeight: "24px", letterSpacing: "0em", fontWeight: "400" }],
        "mono-label": ["11px", { lineHeight: "14px", letterSpacing: "0.05em", fontWeight: "600" }],
        "body-md": ["14px", { lineHeight: "20px", letterSpacing: "0em", fontWeight: "400" }],
        h2: ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        h1: ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "500" }],
        h3: ["18px", { lineHeight: "26px", letterSpacing: "-0.01em", fontWeight: "600" }],
      },
      maxWidth: {
        content: "1200px",
      },
    },
  },
  plugins: [forms, containerQueries],
};

export default config;
